name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - prod

defaults:
  run:
    shell: bash

env:
  GPR_LOGIN: "echo \"${{ secrets.GITHUB_TOKEN }}\" | docker login -u \"${{ github.actor }}\" --password-stdin docker.pkg.github.com"
  GPR_REPO: "docker.pkg.github.com/${{ github.repository }}"
  GPR_TAG: "${GPR_REPO,,}/cache:${NAME}"

jobs:
  gpr:
    name: "${{ matrix.name }}, run ${{ matrix.run }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [gpr]
        run: [1, 2]
      max-parallel: 1
    env:
      NAME: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ env.GPR_LOGIN }}
      - run: docker pull ${{ env.GPR_TAG }} || true
      - run: docker build -t ${{ env.GPR_TAG }} --cache-from=${{ env.GPR_TAG }} .
      - run: docker push ${{ env.GPR_TAG }}
  gpr_tag:
    name: "${{ matrix.name }}, run ${{ matrix.run }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [gpr_tag]
        run: [1, 2]
      max-parallel: 1
    env:
      NAME: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ env.GPR_LOGIN }}
      - run: docker pull ${{ env.GPR_TAG }} || true
      - run: docker build -t ${{ matrix.name }} --cache-from=${{ env.GPR_TAG }} .
      - run: docker tag ${{ matrix.name }} ${{ env.GPR_TAG }} && docker push ${{ env.GPR_TAG }}
  gpr_bk:
    name: "${{ matrix.name }}, run ${{ matrix.run }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [gpr_bk]
        run: [1, 2]
      max-parallel: 1
    env:
      NAME: ${{ matrix.name }}
      DOCKER_BUILDKIT: '1'
    steps:
      - uses: actions/checkout@v2
      - run: ${{ env.GPR_LOGIN }}
      - run: docker build -t ${{ env.GPR_TAG }} --cache-from=${{ env.GPR_TAG }} --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run: docker push ${{ env.GPR_TAG }}
  gpr_bk_tag:
    name: "${{ matrix.name }}, run ${{ matrix.run }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [gpr_bk_tag]
        run: [1, 2]
      max-parallel: 1
    env:
      NAME: ${{ matrix.name }}
      DOCKER_BUILDKIT: '1'
    steps:
      - uses: actions/checkout@v2
      - run: ${{ env.GPR_LOGIN }}
      - run: docker build -t ${{ matrix.name }} --cache-from=${{ env.GPR_TAG }} --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run: docker tag ${{ matrix.name }} ${{ env.GPR_TAG }} && docker push ${{ env.GPR_TAG }}
