name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - prod

defaults:
  name: "${NAME}, run ${{ matrix.run }}"
  run:
    shell: bash
  runs-on: ubuntu-latest
  strategy:
    matrix:
      run: [1, 2]
    max-parallel: 1

env:
  GPR_LOGIN: "echo \"${{ secrets.GITHUB_TOKEN }}\" | docker login -u \"${{ github.actor }}\" --password-stdin docker.pkg.github.com"
  GPR_REPO: "docker.pkg.github.com/${{ github.repository }}"
  GPR_TAG: "${GPR_REPO,,}/cache:${NAME}"

jobs:
  gpr:
    env:
      NAME: gpr
    steps:
      - run: ${{ env.GPR_LOGIN }}
      - run: docker pull ${GPR_TAG} || true
      - run: docker build -t ${GPR_TAG} .
      - run: docker push ${GPR_TAG}
  gpr_tag:
    env:
      NAME: gpr_tag
    steps:
      - run: ${{ env.GPR_LOGIN }}
      - run: docker pull ${GPR_TAG} || true
      - run: docker build -t ${NAME} .
      - run: docker tag ${NAME} ${GPR_TAG} && docker push ${GPR_TAG}
  gpr_bk:
    env:
      NAME: gpr_bk
      DOCKER_BUILDKIT: '1'
    steps:
      - run: ${{ env.GPR_LOGIN }}
      - run: docker build -t ${GPR_TAG} --cache-from=${GPR_TAG} --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run: docker push ${GPR_TAG}
  gpr_bk_tag:
    env:
      NAME: gpr_bk_tag
      DOCKER_BUILDKIT: '1'
    steps:
      - run: ${{ env.GPR_LOGIN }}
      - run: docker build -t ${NAME} --cache-from=${GPR_TAG} --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run: docker tag ${NAME} ${GPR_TAG} && docker push ${GPR_TAG}
